import type { Store, Product, Shop } from "./index";
const photo = (id: string) => `/images/${id}.jpg`;
export const products: Product[] = [
  {
    id: "sony-headphones",
    name: "Sony WH-1000XM5",
    category: "Electronics",
    brand: "Sony",
    description:
      "Your world, beautifully quiet. Industry-leading noise cancellation, exceptional sound, and up to 30 hours of battery life in a lightweight, comfortable design.",
    image: photo("photo-1546435770-a3e426bf472b"),
    rating: 4.8,
    reviews: 128,
    unique: false,
    tags: ["headphones", "audio", "wireless"],
  },
  {
    id: "nike-air",
    name: "Nike Air Max 270",
    category: "Fashion",
    brand: "Nike",
    description:
      "Everyday comfort meets unmistakable style. A breathable upper and signature Air cushioning make every step feel lighter.",
    image: photo("photo-1542291026-7eec264c27ff"),
    rating: 4.7,
    reviews: 86,
    unique: false,
    tags: ["shoes", "sneakers", "running"],
  },
  {
    id: "ceramic-mug",
    name: "Handcrafted ceramic mug",
    category: "Home & Living",
    brand: "Earth & Clay",
    description:
      "Made slowly, enjoyed daily. A wheel-thrown stoneware mug with a natural glaze, handmade by a Bengaluru artisan. Each piece is one of a kind.",
    image: photo("photo-1514228742587-6b1558fcca3d"),
    rating: 4.9,
    reviews: 42,
    unique: true,
    tags: ["coffee", "ceramics", "handmade", "gift"],
  },
  {
    id: "fresh-avocados",
    name: "Farm-fresh avocados · 2 pcs",
    category: "Groceries",
    brand: "Green Basket",
    description:
      "Creamy, naturally ripened avocados sourced from farms in the Western Ghats. Perfect for toast, salads, or your favourite smoothie.",
    image: photo("photo-1523049673857-eb18f1d7b578"),
    rating: 4.6,
    reviews: 64,
    unique: false,
    tags: ["fruit", "organic", "fresh"],
  },
  {
    id: "skincare",
    name: "Daily glow skincare essentials",
    category: "Beauty & Care",
    brand: "Botanica",
    description:
      "A gentle daily ritual. Plant-based cleanser and moisturiser for soft, hydrated skin. Suitable for all skin types.",
    image: photo("photo-1608571423902-eed4a5ad8108"),
    rating: 4.8,
    reviews: 57,
    unique: false,
    tags: ["skin", "natural", "serum"],
  },
  {
    id: "plant",
    name: "Monstera in a ceramic planter",
    category: "Home & Living",
    brand: "Leaf & Life",
    description:
      "A little green goes a long way. A healthy monstera plant in a hand-finished ceramic pot, ready for its new sunny corner.",
    image: photo("photo-1459411552884-841db9b3cc2a"),
    rating: 4.9,
    reviews: 35,
    unique: true,
    tags: ["plant", "garden", "decor"],
  },
  {
    id: "camera",
    name: "Fujifilm Instax Mini 12",
    category: "Electronics",
    brand: "Fujifilm",
    description:
      "Little moments, real memories. Capture spontaneous portraits with automatic exposure and a handy selfie mirror.",
    image: photo("photo-1516035069371-29a1b244cc32"),
    rating: 4.7,
    reviews: 93,
    unique: false,
    tags: ["camera", "photography", "instant"],
  },
  {
    id: "coffee",
    name: "Coorg single-origin coffee · 250g",
    category: "Groceries",
    brand: "Third Wave",
    description:
      "Freshly roasted Arabica from the hills of Coorg. Notes of chocolate and toasted nuts with a smooth finish.",
    image: photo("photo-1559056199-641a0ac8b55e"),
    rating: 4.8,
    reviews: 72,
    unique: true,
    tags: ["coffee", "beans", "local"],
  },
];
export const shops: Shop[] = [
  {
    id: "tech-haven",
    ownerId: "seller-demo",
    name: "Tech Haven",
    description:
      "Your neighbourhood destination for great tech and even better advice. Discover genuine electronics, personal service, and prices worth stepping out for.",
    address: "80 Feet Road, Koramangala, Bengaluru",
    lat: 12.9352,
    lng: 77.6245,
    image: photo("photo-1441986300917-64674bd600d8"),
    rating: 4.8,
    reviews: 214,
    verified: true,
    hours: { open: "09:00", close: "22:00", days: [0, 1, 2, 3, 4, 5, 6] },
    phone: "+91 98765 43210",
    completed: 342,
  },
  {
    id: "neighbourhood-store",
    ownerId: "seller-two",
    name: "The Neighbourhood Store",
    description:
      "Thoughtfully selected everyday essentials from brands we love. Stop by and find something good.",
    address: "5th Block, Koramangala, Bengaluru",
    lat: 12.9315,
    lng: 77.6168,
    image: photo("photo-1473181488821-2d23949a045a"),
    rating: 4.7,
    reviews: 168,
    verified: true,
    hours: { open: "08:00", close: "21:30", days: [0, 1, 2, 3, 4, 5, 6] },
    phone: "+91 98765 43211",
    completed: 208,
  },
  {
    id: "earth-clay",
    ownerId: "seller-three",
    name: "Earth & Clay Studio",
    description:
      "Objects with a story. Handmade ceramics, beautiful plants, and meaningful gifts created by local makers.",
    address: "12th Main, Indiranagar, Bengaluru",
    lat: 12.9719,
    lng: 77.6412,
    image: photo("photo-1493857671505-72967e2e2760"),
    rating: 4.9,
    reviews: 96,
    verified: true,
    hours: { open: "10:00", close: "20:00", days: [0, 2, 3, 4, 5, 6] },
    phone: "+91 98765 43212",
    completed: 154,
  },
  {
    id: "green-basket",
    ownerId: "seller-four",
    name: "Green Basket",
    description:
      "Fresh from the farm, close to home. Seasonal produce, pantry favourites and locally roasted coffee.",
    address: "HSR Layout, Bengaluru",
    lat: 12.918,
    lng: 77.635,
    image: photo("photo-1542838132-92c53300491e"),
    rating: 4.6,
    reviews: 132,
    verified: true,
    hours: { open: "07:00", close: "22:00", days: [0, 1, 2, 3, 4, 5, 6] },
    phone: "+91 98765 43213",
    completed: 420,
  },
];
export function createSeed(): Store {
  const prices = [24990, 10995, 650, 180, 1299, 899, 7499, 450];
  const listings = products.flatMap((p, i) =>
    [0, 1, 2].map((j) => ({
      id: `listing-${i}-${j}`,
      productId: p.id,
      shopId: shops[(i + j) % shops.length].id,
      price: Math.round(prices[i] * (1 + j * 0.09)),
      stock: 10 + i + j,
      active: true,
    })),
  );
  return {
    users: [],
    products,
    shops,
    listings,
    offers: [
      {
        id: "offer-1",
        listingId: "listing-0-0",
        type: "PERCENT",
        value: 12,
        startsAt: "2025-01-01T00:00:00Z",
        endsAt: "2028-01-01T00:00:00Z",
        enabled: true,
        title: "Your next upgrade, for less",
      },
      {
        id: "offer-2",
        listingId: "listing-1-0",
        type: "PERCENT",
        value: 15,
        startsAt: "2025-01-01T00:00:00Z",
        endsAt: "2028-01-01T00:00:00Z",
        enabled: true,
        title: "A little more spring in your step",
      },
    ],
    transactions: [],
    reviews: [],
    favorites: [],
    sessions: [],
    tokens: [],
    notifications: [],
    requests: [],
    bids: [],
    audits: [],
  };
}
